#include <stdio.h>
#include <stdlib.h> 
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include "lcd/lcd.h"
#include "led/led.h"
#include "switches/switches.h"
#include "fatfs/ff.h"
#include "BMPedded/bmp.h"
#include "BMPedded/bmp_lcd.h"
